apiVersion: extensions/v1beta1
kind: Deployment
metadata:
        name: health-net-trpo
spec:
        replicas: 1
        selector:
                matchLabels:
                        app: flasknode
        template:
                metadata:
                        labels:
                                app: flasknode
                spec:
                        containers:
                                - name: flasknode
                                  image: registry.hub.docker.com/jamiker/trpo
                                  imagePullPolicy: Always
                                  ports:
                                          - containerPort: 5000
